spy_agency/hits/urls.py
from django.urls import path

from .views import HitList, HitUpdate, CreateHit, BulkHits


app_name = 'hits'

urlpatterns = [
    path('', HitList.as_view(), name='list'),
    path('<int:pk>/', HitUpdate.as_view(), name='update'),
    path('create/', CreateHit.as_view(), name='create'),
    path('bulk/', BulkHits.as_view(), name='bulk'),
    ]

spy_agency/spy_agency/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include


urlpatterns = [
    path('django-admin/', admin.site.urls),
    path('hits/', include('hits.urls', namespace='hits')),
    path('', include('users.urls', namespace='users')),
]

spy_agency/hits/models.py
from django.db import models
from django.db.models import Q

from users.models import User


class Hit(models.Model):
    STATUS_CHOICES = [
        ('assigned','Assigned'),
        ('failed','Failed'),
        ('completed','Completed'),
    ]
    assignee = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='assignee',
        limit_choices_to=Q(groups__name__in=['hitman', 'manager'])
    )
    description = models.TextField()
    target = models.CharField(max_length=255)
    status = models.CharField(
        max_length=50,
        choices=STATUS_CHOICES,
        default='assigned'
    )
    creator = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='creator',
        limit_choices_to=Q(groups__name__in=['bigboss', 'manager'])
    )

    def __str__(self):
        return self.target

spy_agency/hits/forms.py
import re
from django import forms
from django.forms import widgets

from .models import Hit
from users.models import User, Manager, Lackey
from core.helpers import get_manager_lackeys


class UpdateHitForm(forms.ModelForm):
    class Meta:
        model = Hit
        fields = ('status', 'assignee',)

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super(UpdateHitForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.error_messages = {'required':'This field is required.'}
            field.widget.attrs['class'] = 'form-control'
        if self.user.groups.filter(name__iexact='manager'):
            lackeys = get_manager_lackeys(self.user)
            lackeys = User.objects.filter(email__in=list(lackeys))
            self.fields['assignee'].queryset = lackeys

    def clean_assignee(self):
        assignee = self.cleaned_data['assignee']
        if assignee.lackey:
            is_active = assignee.lackey.lackey.is_active
        elif assignee.manager:
            is_active = assignee.manager.manager.is_active
        if not is_active:
            raise forms.ValidationError('This user is not active (or dead)')
        return assignee


class CreateHitForm(forms.ModelForm):
    class Meta:
        model = Hit
        exclude = ('creator', 'status',)

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super(CreateHitForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.error_messages = {'required':'This field is required.'}
            field.widget.attrs['class'] = 'form-control'
        if self.user.groups.filter(name__iexact='manager'):
            lackeys = get_manager_lackeys(self.user)
            lackeys = lackeys.filter(lackey__is_active=True)
            lackeys = User.objects.filter(email__in=list(lackeys))
            self.fields['assignee'].queryset = lackeys
        else:
            users = User.objects.all().exclude(is_superuser=True)
            users = users.exclude(email=self.user)
            self.fields['assignee'].queryset = users


class BulkForm(forms.ModelForm):
    class Meta:
        model = Hit
        fields = ('assignee',)

    def __init__(self, *args, **kwargs):
        super(BulkForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.error_messages = {'required':'This field is required.'}
            field.widget.attrs['class'] = 'form-control'
            field.label = ''

    def clean_assignee(self):
        assignee = self.cleaned_data['assignee']
        if assignee.lackey:
            is_active = assignee.lackey.lackey.is_active
        elif assignee.manager:
            is_active = assignee.manager.manager.is_active
        if not is_active:
            raise forms.ValidationError('This user is not active (or dead)')
        return assignee

spy_agency/hits/views.py
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth import logout, views
from django.views.generic import list, edit, CreateView
from braces.views import LoginRequiredMixin, GroupRequiredMixin
from extra_views import ModelFormSetView

from .models import Hit
from users.models import Manager, Lackey, User
from core.helpers import get_manager_lackeys
from .forms import UpdateHitForm, CreateHitForm, BulkForm


class HitList(LoginRequiredMixin, GroupRequiredMixin, list.ListView):
    group_required = ('bigboss', 'manager', 'hitman')
    template_name = 'hits/hits_list.html'
    paginate_by = 10
    model = Hit
    login_url = "/login"

    def get_context_data(self, **kwargs):
        context = super(HitList, self).get_context_data(**kwargs)
        return context

    def get_queryset(self):
        order = Hit.objects.all().order_by('-id')
        if not self.request.user.is_superuser:
            group = self.request.user.groups.get().name
            if group == 'hitman':
                list = Hit.objects.filter(assignee=self.request.user)
            elif group == 'manager':
                assignee_list = Hit.objects.filter(assignee=self.request.user)
                creator_list = Hit.objects.filter(creator=self.request.user)
                lackeys = get_manager_lackeys(self.request.user)
                lackeys = User.objects.filter(email__in=lackeys)
                hits_lackeys = Hit.objects.filter(assignee__in=lackeys)
                list = assignee_list.union(creator_list, hits_lackeys)
            elif group == 'bigboss':
                list = Hit.objects.all()
        else:
            list = Hit.objects.all()
        list = list.order_by('-id')
        return list


class HitUpdate(LoginRequiredMixin, GroupRequiredMixin, edit.UpdateView):
    group_required = ('bigboss', 'manager', 'hitman')
    template_name = 'hits/hit_update.html'
    model = Hit
    form_class = UpdateHitForm
    login_url = "/login"

    def get_form_kwargs(self):
        kwargs = super(HitUpdate, self).get_form_kwargs()
        kwargs['use_required_attribute'] = False
        kwargs.update({'user': self.request.user})
        return kwargs

    def form_valid(self, form):
        hit = form.save(commit=False)
        if hit.status == 'failed':
            hit.assignee.is_active = False
            hit.assignee.save()
        messages.success(
            self.request,
            'Hit with id " %s "  has been successfully updated.' % hit.id
        )
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, 'Oops. Please, check the required fields.')
        return super().form_invalid(form)

    def get_success_url(self):
        return reverse('hits:list')


class CreateHit(LoginRequiredMixin, GroupRequiredMixin, CreateView):
    group_required = ('bigboss', 'manager')
    template_name = 'hits/create_hit.html'
    form_class = CreateHitForm
    success_url = '/list'
    login_url = "/login"

    def get_form_kwargs(self):
        kwargs = super(CreateHit, self).get_form_kwargs()
        kwargs['use_required_attribute'] = False
        kwargs.update({'user': self.request.user})
        return kwargs

    def form_valid(self, form):
        hit = form.save(commit=False)
        hit.creator = self.request.user
        group = self.request.user.groups.get().name
        if group == 'manager':
            manager_email = Manager.objects.get(
                                            manager__email=self.request.user)
            lackey_email = User.objects.get(email=hit.assignee)
            lackey = Lackey()
            lackey.manager = manager_email
            lackey.lackey = lackey_email
        else:
            hit.save()
        messages.success(
            self.request,
            'Hit to target " %s "  has been successfully created.' % hit
        )
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, 'Oops. Please, check the required fields.')
        return super().form_invalid(form)

    def get_success_url(self):
        return reverse('hits:list')


class BulkHits(LoginRequiredMixin, GroupRequiredMixin, ModelFormSetView):
    group_required = ('bigboss', 'manager')
    model = Hit
    template_name = 'hits/bulk_hits.html'
    form_class = BulkForm
    success_url = '/list'
    factory_kwargs = {'extra': 0}


    def get_queryset(self):
        if not self.request.user.is_superuser:
            group = self.request.user.groups.get().name
            if group == 'manager':
                assignee_list = Hit.objects.filter(assignee=self.request.user)
                creator_list = Hit.objects.filter(creator=self.request.user)
                creator_list = creator_list.filter(status='assigned')
                list = assignee_list.union(creator_list)
            elif group == 'bigboss':
                list = Hit.objects.filter(status='assigned')
        else:
            list = Hit.objects.all()
        return list

    def construct_formset(self):
        formsets = super(BulkHits, self).construct_formset()
        if not self.request.user.is_superuser:
            group = self.request.user.groups.get().name
            lackeys = get_manager_lackeys(self.request.user)
            if group == 'manager':
                users = User.objects.filter(email__in=lackeys)
            elif group == 'bigboss':
                users = User.objects.all().exclude(is_superuser=True)
                users = users.exclude(email=self.request.user)
            for formset in formsets:
                formset.fields['assignee'].queryset = users
        return formsets

    def formset_valid(self, formset):
        formset.save()
        messages.success(self.request,'Hit has been successfully reassigned.')
        return super().formset_valid(formset)

    def formset_invalid(self, formset):
        messages.error(self.request, 'Oops. Please, check the required fields.')
        return super().formset_invalid(formset)

    def get_success_url(self):
        return reverse('hits:list')

spy_agency/templates/hits/bulk_hits.html
{% extends "base.html" %}
{% load static %}
{% load users_tags %}

{% block title %}Bulk Hits{% endblock %}

{% block content %}

<section>
	{% if messages %}
		 {% for message in messages %}
			 <div class="alert alert-dismissible alert-{{ message.tags }}">
				 <button type="button" class="close" data-dismiss="alert">
				 ×
				 </button>
				 <strong>{{message}}<strong>
			 </div>
		{% endfor %}
	 {% endif %}
	<div class="table-hits table-responsive">
		<form method="post" autocomplete="off">
			{% csrf_token %}
		<table id ="bulk-table" class="table table-hover table-dark">
			<thead>
					<tr>
						<th colspan="6" scope="col"><i class="fa fa-list"></i> ACTIVE HITS</th>
					</tr>
			    <tr>
						<th scope="col">#</th>
			     	<th scope="col">ASIGNEE</th>
			     	<th scope="col">TARGET</th>
			     	<th scope="col">DESCRIPTION</th>
			     	<th scope="col">STATUS</th>
			     	<th scope="col">CREATOR</th>
			    </tr>
		  	</thead>
		  	<tbody>
						{{ formset.management_form }}
						{% for form in formset %}
							<tr>
									<td>{{ form.instance.id }}</td>
									<td>{{ form.assignee }}{{ form.id }}{{form.assignee.errors}}</td>
									<td>{{ form.instance.target }}</td>
									<td>{{ form.instance.description }}</td>
									<td>{{ form.instance.get_status_display }}</td>
									<td>{{ form.instance.creator }}</td>
							</tr>
						{% endfor %}
				</tbody>
		</table>
		<input type="submit" value="Bulk" class="pull-right mt-4 btn btn-dark">
		</form>
	</div>
	<nav>
	    {% if is_paginated %}
	        <ul class="pagination">
	            {% if page_obj.has_previous %}
	                <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
	            {% endif %}

	            {% for i in paginator.page_range %}
	                <li {% if page_obj.number == i %} class="active" {% endif %}>
	                    <a href="?page={{i}}">{{ i }}</a>
	                </li>
	            {% endfor %}

	            {% if page_obj.has_next %}
	                <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
	            {% endif %}
	        </ul>
	    {% endif %}
	</nav>
{% endblock %}

spy_agency/templates/hits/create_hit.html
{% extends "base.html" %}
{% load static %}

{% block title %}Create Hit{% endblock %}

{% block content %}
	<section>
		{% if messages %}
			 {% for message in messages %}
				 <div class="alert alert-dismissible alert-{{ message.tags }}">
					 <button type="button" class="close" data-dismiss="alert">
					 ×
					 </button>
					 <strong>{{message}}<strong>
				 </div>
			{% endfor %}
		 {% endif %}
		<form method="post" autocomplete="off">
			{% csrf_token %}
			<div class="form-group row">
		    <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm">Target</label>
		    <div class="col-sm-10">
		      {{ form.target }}
					{{form.target.errors}}
		    </div>
		  </div>
			<div class="form-group row">
		    <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm">Description</label>
		    <div class="col-sm-10">
		      {{ form.description }}
					{{ form.description.errors }}
		    </div>
		  </div>
			<div class="form-group row">
		    <label for="colFormLabelSm" class="col-sm-2 col-form-label col-form-label-sm">Asignee</label>
		    <div class="col-sm-10">
		      {{ form.assignee }}
					{{ form.assignee.errors }}
		    </div>
		  </div>
      <input type="submit" value="Create hit" class="pull-right mt-4 btn btn-dark">
		</form>
	</section>
{% endblock %}

spy_agency/templates/hits/hit_update.html
{% extends "base.html" %}
{% load static %}
{% load users_tags %}

{% block title %}Hit details{% endblock %}

{% block content %}
	<section>
		{% if messages %}
			 {% for message in messages %}
				 <div class="alert alert-dismissible alert-{{ message.tags }}">
					 <button type="button" class="close" data-dismiss="alert">
					 ×
					 </button>
					 <strong>{{message}}<strong>
				 </div>
			{% endfor %}
		 {% endif %}
		<form method="post" autocomplete="off" novalidate>
			{% csrf_token %}
			<div class="card w-75 mx-auto h-100">
				<div class="card-header">
					<h4><i class="fa fa-user-circle"></i> HIT DETAILS</h4>
				</div>
				<div class="card-body">
					<dl class="row">
						<dt class="col-sm-7">Creator:</dt>
						<dd class="col-sm-5">{{ object.creator }}</dd>
					</dl>
					<dl class="row">
						<dt class="col-sm-7">Asignee:</dt>
						<dd class="col-sm-5">
							{% if not request.user|has_group:'hitman' %}
								{% if object.status == 'assigned'%}
									{{ form.assignee }}
									{{ form.assignee.errors }}
								{% else %}
									{% if form.assignee.errors %}
										{{form.assignee}}
										{{ form.assignee.errors }}
									{% else %}
										{{ object.assignee }}
									{% endif %}
								{% endif %}
							{% else %}
								{{ object.assignee }}
							{% endif %}
						</dd>
					</dl>
					<dl class="row">
						<dt class="col-sm-7">Target:</dt>
						<dd class="col-sm-5">{{ object.target }}</dd>
					</dl>
					<dl class="row">
						<dt class="col-sm-7">Description:</dt>
						<dd class="col-sm-5">{{ object.description }}</dd>
					</dl>
					<dl class="row">
						<dt class="col-sm-7">Status:</dt>
						<dd class="col-sm-5">
							{% if object.status == 'assigned'%}
								{{ form.status }}
								{{ form.status.errors }}
							{% else %}
								{% if form.assignee.errors %}
									{{form.status}}
								{% else %}
									{{ object.get_status_display }}
								{% endif %}
							{% endif %}
						</dd>
					</dl>
				</div>
			</div>
			{% if object.status == 'assigned' %}
				<input type="submit" value="Update" class="pull-right mt-4 btn btn-dark">
			{% else %}
				{% if form.assignee.errors %}
					<input type="submit" value="Update" class="pull-right mt-4 btn btn-dark">
				{% endif %}
			{% endif %}
		</form>
	</section>
{% endblock %}

spy_agency/templates/hits/hits_list.html
{% extends "base.html" %}
{% load static %}
{% load users_tags %}

{% block title %}Hits List{% endblock %}

{% block content %}
{% if not request.user|has_group:'hitman' %}
	<div id="create_hit" class="pull-right mt-4 mb-4">
		<a class="btn btn-dark" href="{% url 'hits:create' %}" role="button"><i class="fa fa-plus-circle"></i> Create Hit</a>
	</div>
{% endif %}
<section>
	{% if messages %}
		 {% for message in messages %}
			 <div class="alert alert-dismissible alert-{{ message.tags }}">
				 <button type="button" class="close" data-dismiss="alert">
				 ×
				 </button>
				 <strong>{{message}}<strong>
			 </div>
		{% endfor %}
	 {% endif %}
	<div class="table-hits table-responsive">
		<table class="table table-hover table-dark">
			<thead>
					<tr>
						<th colspan="6" scope="col"><i class="fa fa-list"></i> HITS</th>
					</tr>
			    <tr>
						<th scope="col">#</th>
			     	<th scope="col">ASIGNEE</th>
			     	<th scope="col">TARGET</th>
			     	<th scope="col">DESCRIPTION</th>
			     	<th scope="col">STATUS</th>
			     	<th scope="col">CREATOR</th>
			    </tr>
		  	</thead>
		  	<tbody>
		    {% for hit in object_list %}
			    <tr>
							<td><a href="{% url 'hits:update' hit.pk %}">{{ hit.id }}</a></td>
			        <td>{{ hit.assignee }}</td>
			        <td>{{ hit.target }}</td>
			        <td>{{ hit.description }}</td>
			        <td>{{ hit.get_status_display }}</td>
			        <td>{{ hit.creator }}</td>
			    </tr>
		    {% empty %}
		        <tr>
		            <td colspan="6" align="center">No pending jobs.</td>
		        </tr>
		    {% endfor %}
		  	</tbody>
		</table>
	</div>

	<nav>
	    {% if is_paginated %}
	        <ul class="pagination">
	            {% if page_obj.has_previous %}
	                <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
	            {% endif %}

	            {% for i in paginator.page_range %}
	                <li {% if page_obj.number == i %} class="active" {% endif %}>
	                    <a href="?page={{i}}">{{ i }}</a>
	                </li>
	            {% endfor %}

	            {% if page_obj.has_next %}
	                <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
	            {% endif %}
	        </ul>
	    {% endif %}
	</nav>
</section>
{% endblock %}