spy_agency/hits/urls.py
from django.urls import path

from .views import HitList, HitUpdate, CreateHit, BulkHits


app_name = 'hits'

urlpatterns = [
    path('', HitList.as_view(), name='list'),
    path('<int:pk>/', HitUpdate.as_view(), name='update'),
    path('create/', CreateHit.as_view(), name='create'),
    path('bulk/', BulkHits.as_view(), name='bulk'),
    ]

spy_agency/spy_agency/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include


urlpatterns = [
    path('django-admin/', admin.site.urls),
    path('hits/', include('hits.urls', namespace='hits')),
    path('', include('users.urls', namespace='users')),
]

spy_agency/users/urls.py
from django.urls import path, reverse_lazy

from .views import (LoginView, LogoutView, SignUpView, UsersListView,
                    UserUpdate, UpdateLackeyView)


app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(redirect_authenticated_user=True,
                                    next_page=reverse_lazy('hits_list')),
                                    name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', SignUpView.as_view(), name='register'),
    path('hitmen/', UsersListView.as_view(), name='hitmen'),
    path('hitmen/<int:pk>/', UserUpdate.as_view(), name='update'),
    path('lackey/<int:pk>/', UpdateLackeyView.as_view(), name='update_lackey'),
]

spy_agency/templates/_navbar.html
{% load static %}
{% load users_tags %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'hits:list' %}"><i class="fa fa-user-secret"></i> Spy Agency
</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {% if request.path == '/hits/' %}active{% endif %}">
        <a class="nav-link" href="{% url 'hits:list' %}">Hits</a>
      </li>
      {% if not request.user|has_group:'hitman' %}
      <li class="nav-item {% if request.path == '/hits/bulk/' %}active{%endif%}">
        <a class="nav-link" href="{% url 'hits:bulk' %}">Bulk</a>
      </li>
      <li class="nav-item {% if request.path == '/hitmen/' %}active{%endif%}">
        <a class="nav-link" href="{% url 'users:hitmen' %}">My people</a>
      </li>
      {% endif %}
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li class="mr-4">Hi, {{request.user.username}} ({{user.groups.all.0}})</li>
      <li><a href="{% url 'users:logout' %}"><i class="fa fa-sign-out" aria-hidden="true"></i>Logout</a></li>
    </ul>
  </div>
</nav>

spy_agency/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="x-ua-compatible" content="ie=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{% endblock %}</title>
        <link rel="icon" href="{% static 'img/favicon.ico' %}" />
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />
        <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    </head>
    <body>
      <header>
        {% if user.is_authenticated %}
          {% include "_navbar.html" %}
        {% endif %}
      </header>
        <div class="container">
            {% block content %}{% endblock %}
        </div>
        <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        {% block extra_scripts %}{% endblock %}
    </body>
</html>