spy_agency/hits/urls.py
from django.urls import path

from .views import HitList, HitUpdate, CreateHit, BulkHits


app_name = 'hits'

urlpatterns = [
    path('', HitList.as_view(), name='list'),
    path('<int:pk>/', HitUpdate.as_view(), name='update'),
    path('create/', CreateHit.as_view(), name='create'),
    path('bulk/', BulkHits.as_view(), name='bulk'),
    ]

spy_agency/spy_agency/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include


urlpatterns = [
    path('django-admin/', admin.site.urls),
    path('hits/', include('hits.urls', namespace='hits')),
    path('', include('users.urls', namespace='users')),
]

spy_agency/users/urls.py
from django.urls import path, reverse_lazy

from .views import (LoginView, LogoutView, SignUpView, UsersListView,
                    UserUpdate, UpdateLackeyView)


app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(redirect_authenticated_user=True,
                                    next_page=reverse_lazy('hits_list')),
                                    name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', SignUpView.as_view(), name='register'),
    path('hitmen/', UsersListView.as_view(), name='hitmen'),
    path('hitmen/<int:pk>/', UserUpdate.as_view(), name='update'),
    path('lackey/<int:pk>/', UpdateLackeyView.as_view(), name='update_lackey'),
]

spy_agency/users/models.py
from django.db import models
from django.db.models import Q
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import AbstractUser, Group
from functools import wraps


class User(AbstractUser):
    email = models.EmailField(unique=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.email

class Manager(models.Model):
    manager = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name='manager',
        limit_choices_to=Q(groups__name='manager')
    )

    def __str__(self):
        return self.manager.email


class Lackey(models.Model):
    manager = models.ForeignKey(
        Manager,
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )
    lackey = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name='lackey',
        null=True,
        blank=True,
        limit_choices_to=Q(groups__name='hitman')
    )

    def __str__(self):
        return self.lackey.email


@receiver(post_save, sender=User)
def add_group_to_user(sender, instance, created, **kwargs):
    if created:
        instance.groups.add(Group.objects.get(name='hitman'))


def disable_for_loaddata(signal_handler):
    """
    Decorator that turns off signal handlers when loading fixture data.
    """

    @wraps(signal_handler)
    def wrapper(*args, **kwargs):
        if kwargs['raw']:
            return
        signal_handler(*args, **kwargs)
    return wrapper


@receiver(post_save, sender=User)
@disable_for_loaddata
def create_lackey(sender, instance, created, **kwargs):
    if created:
        lackey = Lackey()
        lackey.lackey = instance
        lackey.save()

spy_agency/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from extra_views import InlineFormSetFactory

from .models import User, Lackey


class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2',)
        widgets = {
            'email': forms.EmailInput(
                attrs={
                    'class':'input', 'placeholder': 'Email Address'
                }
            ),

        }


class UpdateUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('is_active',)


class LackeyForm(forms.ModelForm):
    class Meta:
        model = Lackey
        fields = ('manager',)

    def __init__(self, *args, **kwargs):
        super(LackeyForm, self).__init__(*args, **kwargs)
        self.fields['manager'].required = True
        for field in self.fields.values():
            field.error_messages = {'required':'This field is required.'}

spy_agency/users/views.py
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth import logout, views
from django.views.generic import RedirectView, edit, list
from braces.views import LoginRequiredMixin, GroupRequiredMixin
from extra_views import UpdateWithInlinesView

from .forms import UserRegistrationForm, UpdateUserForm, LackeyForm
from .models import User, Manager, Lackey
from core.helpers import get_manager_lackeys


class LoginView(views.LoginView):
    template_name = 'user/login.html'
    next_page = None

    def get_form_kwargs(self):
        kwargs = super(LoginView, self).get_form_kwargs()
        kwargs['use_required_attribute'] = False
        return kwargs

    def get_success_url(self):
        return self.get_redirect_url() or self.get_default_redirect_url()

    def get_default_redirect_url(self):
        """Return the default redirect URL."""
        return reverse('hits:list')


class LogoutView(RedirectView):
    pattern_name = 'users:login'

    def get(self, request, *args, **kwargs):
        logout(request)
        return super(LogoutView, self).get(request, *args, **kwargs)


class SignUpView(edit.CreateView):
    template_name = 'user/register.html'
    success_url = '/login'
    form_class = UserRegistrationForm

    def get_form_kwargs(self):
        kwargs = super(SignUpView, self).get_form_kwargs()
        kwargs['use_required_attribute'] = False
        return kwargs

    def form_valid(self, form):
        user = form.save(commit=False)
        user.username = user.email.split('@')[0]        
        messages.success(
            self.request,
            'User " %s "  has been successfully created.' % user
        )
        return super().form_valid(form)


class UsersListView(LoginRequiredMixin, GroupRequiredMixin, list.ListView):
    group_required = ('bigboss', 'manager',)
    template_name = 'user/users_list.html'
    paginate_by = 10
    model = User
    login_url = "/login"

    def get_queryset(self):
        if not self.request.user.is_superuser:
            group = self.request.user.groups.get().name
            if group == 'manager':
                manager = Manager.objects.filter(
                                            manager__email=self.request.user)
                lackeys = Lackey.objects.filter(manager__in=manager)
                users_list = lackeys
            elif group == 'bigboss':
                users_list = User.objects.all().exclude(is_superuser=True)
                users_list = users_list.exclude(email=self.request.user)
        else:
            users_list = User.objects.all().exclude(is_superuser=True)
        return users_list.order_by('id')


class UserUpdate(LoginRequiredMixin, GroupRequiredMixin, edit.UpdateView):
    group_required = ('bigboss', 'manager',)
    template_name = 'user/user_update.html'
    form_class = UpdateUserForm
    model = User
    login_url = "/login"

    def get_form_kwargs(self):
        kwargs = super(UserUpdate, self).get_form_kwargs()
        kwargs['use_required_attribute'] = False
        return kwargs

    def get_context_data(self, **kwargs):
        context = super(UserUpdate, self).get_context_data(**kwargs)
        manager = Manager.objects.filter(manager__email=self.get_object())
        manager = manager.values_list('id', flat=True)
        lackeys = Lackey.objects.filter(manager__in=manager)
        context['lackeys_list'] = lackeys
        return context

    def form_valid(self, form):
        user = form.save()
        messages.success(
            self.request,
            'User "%s"  has been successfully updated.' % user.username
        )
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('users:hitmen')


class UpdateLackeyView(LoginRequiredMixin, GroupRequiredMixin, edit.UpdateView):
    group_required = ('bigboss', 'manager',)
    model = Lackey
    form_class = LackeyForm
    template_name = 'user/update_lackey.html'

    def get_form_kwargs(self):
        kwargs = super(UpdateLackeyView, self).get_form_kwargs()
        kwargs['use_required_attribute'] = False
        return kwargs

    def get_success_url(self):
        return reverse('users:hitmen')

    def form_valid(self, form):
        user = form.save()
        messages.success(
            self.request,
            'User "%s"  has been successfully updated.' % user.lackey.username
        )
        return super().form_valid(form)

spy_agency/templates/user/login.html
{% extends "base.html" %}
{% load static %}
{% load users_tags %}

{% block title %}Login{% endblock %}

{% block content %}
{% if messages %}
   {% for message in messages %}
     <div class="alert alert-dismissible alert-{{ message.tags }}">
       <button type="button" class="close" data-dismiss="alert">
       ×
       </button>
       <strong>{{message}}<strong>
     </div>
  {% endfor %}
 {% endif %}
<section id="login">
  <div class="d-flex justify-content-center h-100">
  		<div class="card">
  			<div class="card-header">
          <h3><i class="fa fa-user-secret"></i> Sign In</h3>
  			</div>
  			<div class="card-body">
          <form method="POST">
              {% csrf_token %}
  					<div class="input-group form-group">
  						<div class="input-group-prepend">
  							<span class="input-group-text"><i class="fa fa-user"></i></span>
  						</div>
              <div>
                  {{ form.username|add_class:"form-control" }}
              </div>
              <div>
                  {{ form.username.errors }}
              </div>
  					</div>
  					<div class="input-group form-group">
  						<div class="input-group-prepend">
  							<span class="input-group-text"><i class="fa fa-key"></i></span>
  						</div>
              <div>
                  {{ form.password|add_class:"form-control" }}
              </div>
              <div>
                  {{ form.password.errors }}
              </div>
  					</div>
  					<div class="form-group">
  						<input type="submit" value="Login" class="btn login_btn">
  					</div>
  				</form>
  			</div>
  			<div class="card-footer">
  				<div class="d-flex justify-content-center links">
  					<span>Don't have an account?&nbsp;</span><a href="{% url 'users:register' %}">Sign Up</a>
  				</div>
  			</div>
  		</div>
  	</div>

</section>
{% endblock %}

spy_agency/templates/user/register.html
{% extends "base.html" %}
{% load static %}
{% load users_tags %}

{% block title %}Login{% endblock %}

{% block content %}
<section id="login">
  <div class="d-flex justify-content-center h-100">
  		<div class="card">
  			<div class="card-header">
          <h3><i class="fa fa-user-secret"></i> Sign Up</h3>
  			</div>
  			<div class="card-body">
          <form method="POST">
              {% csrf_token %}
  					<div class="input-group form-group">
  						<div class="input-group-prepend">
  							<span class="input-group-text"><i class="fa fa-user"></i></span>
  						</div>
              <div>
                  {{ form.email|add_class:"form-control" }}
              </div>
              {{ form.email.errors }}
  					</div>
  					<div class="input-group form-group">
  						<div class="input-group-prepend">
  							<span class="input-group-text"><i class="fa fa-key"></i></span>
  						</div>
              <div>
                  {{ form.password1|add_class:"form-control" }}
              </div>
              {{ form.password1.errors }}
  					</div>
            <div class="input-group form-group">
  						<div class="input-group-prepend">
  							<span class="input-group-text"><i class="fa fa-key"></i></span>
  						</div>
              <div>
                  {{ form.password2|add_class:"form-control" }}
              </div>
              {{ form.password2.errors }}
  					</div>
  					<div class="form-group">
  						<input type="submit" value="Sign Up" class="btn login_btn">
  					</div>
  				</form>
  			</div>
        <div class="card-footer">
  				<div class="d-flex justify-content-center">
  					<span>Still not a hit man?</span>
  				</div>
  			</div>
  		</div>
  	</div>

</section>
{% endblock %}

spy_agency/templates/user/update_lackey.html
{% extends "base.html" %}
{% load static %}
{% load users_tags %}

{% block title %}Update User{% endblock %}

{% block content %}
	<section>
		<form method="post">
        {% csrf_token %}

				<div class="card w-75 mx-auto h-100">
					<div class="card-header">
						<h4><i class="fa fa-user-circle"></i> {{form.instance.lackey}}</h4>
					</div>
            <div class="card-body">
							<dl class="row">
								<dt class="col-sm-7">Username:</dt>
								<dd class="col-sm-5">{{form.instance.lackey.username}}</dd>
							</dl>
							<dl class="row">
								<dt class="col-sm-7">Email:</dt>
								<dd class="col-sm-5">{{form.instance.lackey.email}}</dd>
							</dl>
							<dl class="row">
								<dt class="col-sm-7">Role:</dt>
								<dd class="col-sm-5">{{form.instance.lackey.groups.all.0 }}</dd>
							</dl>
							<dl class="row">
								<dt class="col-sm-7">Manager:</dt>
								<dd class="col-sm-5">{{form.manager}}{{form.manager.errors}}</dd>
							</dl>
            </div>
        </div>
  		<input type="submit" value="Update" class="mt-4 btn btn-dark">
    </form>
	</section>
{% endblock %}

spy_agency/templates/user/user_update.html
{% extends "base.html" %}
{% load static %}
{% load users_tags %}

{% block title %}Update User{% endblock %}

{% block content %}
	<section>
		<form method="post">
        {% csrf_token %}
        <div class="card w-75 mx-auto h-100">
					<div class="card-header">
						<h4><i class="fa fa-user-circle"></i> {{form.instance.username}}</h4>
					</div>
            <div class="card-body">
							<dl class="row">
								<dt class="col-sm-7">Username:</dt>
								<dd class="col-sm-5">{{form.instance.username}}</dd>
							</dl>
							<dl class="row">
								<dt class="col-sm-7">Email:</dt>
								<dd class="col-sm-5">{{form.instance.email}}</dd>
							</dl>
							{% if request.user|has_group:'bigboss' %}
								<dl class="row">
									<dt class="col-sm-7">Role:</dt>
									<dd class="col-sm-5">{{form.instance.groups.all.0 }}</dd>
								</dl>
								{% if not form.instance.manager.manager %}
								<dl class="row">
									<dt class="col-sm-7">Assigned to:</dt>
									<dd class="col-sm-5">
										{% if form.instance.lackey.manager %}
											{{form.instance.lackey.manager}}
											{% if form.instance.is_active %}
											<br>
											<a href="{% url 'users:update_lackey' form.instance.lackey.id %}">Reassign to another manager</a>
											{% endif %}
										{% else %}
												<span class="text-danger">Not assigned</span><br>
												<a href="{% url 'users:update_lackey' form.instance.lackey.id %}">Assign to a manager</a>
										{% endif %}
									</dd>
								</dl>
								{% else %}
									<dl class="row">
										<dt class="col-sm-7">Lackeys:</dt>
										<dd class="col-sm-5">
											{% for lackey in lackeys_list %}
												{{lackey}}
											{% endfor %}<br>
											</dd>
									</dl>
								{% endif %}
							{% endif %}
							<dl class="row">
								<dt class="col-sm-7">Last login:</dt>
								<dd class="col-sm-5">{{form.instance.last_login }}</dd>
							</dl>
							<dl class="row">
								<dt class="col-sm-7">Date joined:</dt>
								<dd class="col-sm-5">{{form.instance.date_joined }}</dd>
							</dl>
							<dl class="row">
								 <dt class="col-sm-7">Is this {{form.instance.groups.all.0 }} still alive?</dt>
							  <dd class="col-sm-5">
									{% if not form.instance.is_active %}
										{{form.instance.groups.all.0 }} is dead or inactive.
									{% else %}
										{{form.is_active}}
									{% endif %}
								</dd>
							</dl>
									{{form.is_active.errors}}
            </div>
        </div>
				{% if form.instance.is_active %}
	        <div class="mt-3 mb-5">
	            <button type="submit" class="mt-4 btn btn-dark">Update</button>
	        </div>
				{% endif %}
    </form>
	</section>
{% endblock %}

spy_agency/templates/user/users_list.html
{% extends "base.html" %}
{% load static %}
{% load users_tags %}

{% block title %}Users List{% endblock %}

{% block content %}
<section>
	{% if messages %}
		 {% for message in messages %}
			 <div class="alert alert-dismissible alert-{{ message.tags }}">
				 <button type="button" class="close" data-dismiss="alert">
				 ×
				 </button>
				 <strong>{{message}}<strong>
			 </div>
		{% endfor %}
	 {% endif %}
	<div class="table-hits table-responsive">
		<table class="table table-hover table-dark">
			<thead>
					<tr>
						<th colspan="5" scope="col"><i class="fa fa-list"></i> MY PEOPLE</th>
					</tr>
			    <tr>
						<th scope="col">#</th>
			     	<th scope="col">USERNAME</th>
			     	<th scope="col">EMAIL</th>
						<th scope="col">STATUS</th>
						{% if request.user|has_group:'bigboss' %}
							<th scope="col">IS ASSIGNED</th>
						{% endif %}
			    </tr>
		  	</thead>
		  	<tbody>
				{% for object in object_list %}
					{% if request.user|has_group:'manager' %}
				    <tr>
								<td><a href="{% url 'users:update' object.lackey_id %}">{{object.lackey_id}}</a></td>
				        <td>{{ object.lackey.username }}</td>
								<td>{{ object.lackey.email }}</td>
								<td>{% if object.lackey.is_active %}Is alive{% else %}<span class="text-danger">Is dead</span>{% endif %}</td>
				    </tr>
					{% else %}
					<tr>
							<td><a href="{% url 'users:update' object.id %}">{{object.id}}</a></td>
							<td>{{ object.username }}</td>
							<td>{{ object.email }}</td>
							<td>{% if object.is_active %}Is alive{% else %}<span class="text-danger">Is dead</span>{% endif %}</td>
							<td>
								{% if object.lackey.manager %}
									{{object.lackey.manager}}
								{% else %}
									{% if object.manager.manager %}
										He is a manager
									{% else %}										
										<span class="text-danger">Not assigned</span>
									{% endif %}
								{% endif %}
							</td>
					</tr>
					{% endif %}
				{% endfor %}
		  	</tbody>
		</table>
	</div>

	<nav>
	    {% if is_paginated %}
	        <ul class="pagination">
	            {% if page_obj.has_previous %}
	                <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
	            {% endif %}

	            {% for i in paginator.page_range %}
	                <li {% if page_obj.number == i %} class="active" {% endif %}>
	                    <a href="?page={{i}}">{{ i }}</a>
	                </li>
	            {% endfor %}

	            {% if page_obj.has_next %}
	                <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
	            {% endif %}
	        </ul>
	    {% endif %}
	</nav>
</section>
{% endblock %}